// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRFdKJTPN7i8iWxtiUtOp0VcHmmOKJXJw',
    appId: '1:728690184400:android:d5cf77d0ec6ac19e3c0ed5',
    messagingSenderId: '728690184400',
    projectId: 'aeolus-cfb71',
    storageBucket: 'aeolus-cfb71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWulUaGOckdxcNA1eFyFWfhpRQUT4xS58',
    appId: '1:728690184400:ios:82abc63c1ac8beb73c0ed5',
    messagingSenderId: '728690184400',
    projectId: 'aeolus-cfb71',
    storageBucket: 'aeolus-cfb71.appspot.com',
    androidClientId: '728690184400-fgjr523qrq1p03rmsg4qiom4cgsaljbd.apps.googleusercontent.com',
    iosClientId: '728690184400-cchc96rvjkm2lkm5j3snfscacpf19r6k.apps.googleusercontent.com',
    iosBundleId: 'com.manthan.aeolus',
  );

}